---
- hosts: amazonweb
  become: yes
  tasks:
    - name: 'install java'
      yum: name=java-1.8.0 state=present

    - name: 'download tomcat tar file'
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.0/bin/apache-tomcat-8.5.0.tar.gz
        dest: /opt

    - name: 'unarchive tar file'
      unarchive:
        src: /opt/apache-tomcat-8.5.0.tar.gz
        dest: /opt
        remote_src: yes

    - name: 'remove tar file from ansible worker or ansible nodes'
      shell: rm -rf /opt/apache-tomcat-8.5.0.tar.gz warn=false

    - name: 'start tomcat service'
      command: nohup /opt/apache-tomcat-8.5.0/bin/startup.sh
